### PR TITLE
Fix/efs ipv6

### LINKED ISSUE #1640: Support EFS CSI Driver for IPv6 cluster
**How to categorize this issue?**

/area bug
/kind enhancement
/platform aws

**What would you like to be added**:
Enabling the EFS CSI Driver in an IPv6-only cluster currently fails, even though it is expected to work the same way as in IPv4 or dual-stack environments. 
The driver itself does not require any IPv6-specific configuration.
However, a few infrastructure adjustments are required:
- The EFS file system must have mount targets with IPv6 addresses, created in subnets that are assigned IPv6 CIDR blocks.
- The security group attached to the EFS mount targets must allow IPv6 ingress traffic (TCP port 2049) from the cluster’s IPv6 address range.

### PR DESCRIPTION
**Pull request by hebelsan**
**How to categorize this PR?**

/area quality
/kind bug
/platform aws

**What this PR does / why we need it**:
This PR fixes EFS support in IPv6-only clusters.

In IPv6 clusters, IPv6 EFS mount targets are now created.
The EFS controller is configured with AWS_EC2_METADATA_SERVICE_ENDPOINT_MODE=IPv6.
Finally, this PR enables the IPv6 IMDS endpoint on the instances when the cluster is IPv6-only.

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener-extension-provider-aws/issues/1640

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
Support EFS in IPv6 only cluster.
```

### CODE REVIEW

**Comment by hebelsan** [comment]
Since the MCM PR has been merged and released, this PR is now ready for review.

File: pkg/aws/client/client.go [hunk 1]
```diff
@@ -2299,57 +2300,67 @@ func (c *Client) FindFileSystemsByTags(ctx context.Context, tags Tags) ([]*efsty
...
 
-	var fsDescription *efstypes.FileSystemDescription
+	var fsDescription *efs.DescribeFileSystemsOutput
 	err = c.PollImmediateUntil(ctx, func(ctx context.Context) (bool, error) {
-		fsDescription, err = c.GetFileSystem(ctx, fID)
-		if err != nil {
+		fsDescription, err = c.EFS.DescribeFileSystems(ctx, &efs.DescribeFileSystemsInput{
+			FileSystemId: aws.String(fID),
+		})
+		if ignoreNotFound(err) != nil {
```
Comment (AndreasBurger) [inline pkg/aws/client/client.go:2335]: We should've used `IsNotFoundError` consitently for this 🫤.

Something to keep in mind for future work on this file.

**Review by AndreasBurger — COMMENTED** [review]
LGTM

/approve

**Review by AndreasBurger — APPROVED** [review]
